### ISSUE TITLE
Allow RFC7396 Json Merge PATCH

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1021]
Our `/PATCH/{kind}/{id}` currently only supports [RFC 6902](https://tools.ietf.org/html/rfc6902) patch semantics which are cumbersome to use and often not intuitive.

[RFC 7396](https://tools.ietf.org/html/rfc7396) has introduced a much more natural json merge syntax which should make partial updates much more intuitive.

## Goal
* Implement without breaking change
* Accept merge document if Header `Content-Type: application/merge-patch+json` is set
* Merge as atomically as possible (try to avoid Read-before-Write pattern and let backend handle the merge if possible)

## Todos
* [x] evaluate: can we recoginze explicit `null` over not set?
  * unfortunately not, while possible in go, we don't have this level of access in `go-swagger`
* [x] build UC
  * [x] split into primitive and ref types
  * [x] verify behavior works for both actions and things
  * [x] make sure typed errors are used for 400/500 distinction
* [x] build API
* [x] build repo
* [ ] take updating of vector position into account
* [ ] can we return the merged payload?
  *  if not, return `204 No Content`
* [x] fix/update journey tests (grep for `gh-1021`)

**Comment by etiennedi** [comment]
Regardless of what the current behavior is: Is there a reason to ever show `"field": null` instead of doing it exactly as described in the RFC document? I can't think of any?

**Comment by fefi42** [comment]
I was just wondering if we even support that. If a class has a field and it is not specified will it not be null by default?
