### ISSUE TITLE
Auto/contextual classification

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1033]
Instead of comparing to labeled data, we simply classify the target that is closest to the source.

## Advantages
* doesn't require labelled data

## Disadvantages
* results will only be good if the description of the sources is logically close to the destination

## Example: 
Sources:
- `Chocolate Cake`
- `Creamy Ganache`
- `Wiener Schintzel`
- `Pizza`

Possible Targets:
- `Savory food`
- `Sweet food`

Goal: Auto assign all sources to the closest possible target 

## API Discussion
can be found in https://github.com/semi-technologies/weaviate/issues/987

## TODOS
* [x] Refactor current classifier to be able to take in different types
* [x] validate differently if `type==contextual`
  * [x] target prop must be ref
  * [x] target prop must be ref to a single class (for now)
* [x] in UC orchestrate NN-search
* [x] add distance metrics to it
* [x] build/adapt required repos
* [x] explorative test using 20news - how does it compare to kNN?
* [x] make sure newly spawned contexts have a timeout
