### ISSUE TITLE
Give user control over vectorization of schema items

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1062]
Based on the discussion in #1047 

# Goals

* [x] By default, no schema items are used (all new options default to `false`)
* [x] If `vectorizeClassName` is set to false
  * [x] the className does not have to be c11y valid
  * [x] the className is not used in vectorization
* [x] if `vectorizeClassName` is set to true
  * [x] the className must be c11y valid - or schema creation will fail
  * [x] the className is used in vectorization
* [x] If `vectorizePropertyName` is set to false
  * [x] the propertyName does not have to be c11y valid
  * [x] the propertyName is not used in vectorization
* [x] if `vectorizePropertyName` is set to true
  * [x] the propertyName must be c11y valid - or schema creation will fail
  * [x] the propertyName is used in vectorization
* [ ] if the user does not want to vectorize any schema items
  * [ ] at least one of the (indexed) property **values** must be contextionary-valid or we fail with a detailed error message **at import time** explaining why the above is not possible
  * [ ] and they set all properties to `noindex` schema creation will fail with a verbose error message explaining why

## Todos

* [x] add new fields to API
* [x] update vectorization
* [x] update schema manager to report correct vectorization state for a class/prop
* [ ] update validation
  * [ ] make contextionary return typed errors, so that we can catch the "no usable words" case: https://github.com/semi-technologies/contextionary/issues/22
* [ ] deal with fallout of "contextionary-schema", do we still need this at all? Can we remove it?
