### ISSUE TITLE
Set custom vetorization weights through API

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1074]
Based on the the discussion in #1070 

Depends on semi-technologies/contextionary#24

## Todos

* [x] Add new object to REST API
* [x] Since it's a map type, parse and validate manually
* [x] Store on save
* [x] Store on update
* [x] Pass along to contextionary when vectorizing
* [x] E2E-Test automatically and/or exploratively

**Comment by etiennedi** [comment]
closed in #1075 (released as 0.22.1)
