### ISSUE TITLE
DataType "phoneNumber" Implemenation

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1088]
## Background

Based on the API discussion in #1087 (still ongoing at the time of this writing).

## Todos

* [x] Add new type to go-swagger models
* [x] Validate and Parse when entering
  * using [nyaruka/phonenumbers](https://github.com/nyaruka/phonenumbers)
  * [x] check license compatibility
     * [MIT License](https://github.com/nyaruka/phonenumbers/blob/master/LICENSE)
   * [x] parse into types using third party lib
   * [x] remove casing requirements of country code
   * [x] what happens if no country code is provided?
     * [x] improve error message over library 
   * [x] validate validation with unit tests
* [x] store with the correct internal field types in backend
* [x] display correctly in REST API
* [x] display correctly in GraphQL API
* [x] extend e2e test with phone number test

## Out of scope
* search by phone number, implementation in #1089 
* aggregations on phone numbers (TODO: Open issue)
