### ISSUE TITLE
Linkable References in REST API

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1106]
Additionally to the beacon also show an http (`href`) link to directly reference the linked resource.

## Todos
* [x] enrich `GET /things/{id}`
* [x] enrich `GET /actions/{id}`
* [x] enrich `GET /things`
* [x] enrich `GET /actions`
* [x] enrich returns of `PUT /things/{id}`
* [x] enrich returns of `PUT /actions/{id}`
* [x] show origin (absolute URI) if set, relative URI otherwise
