### ISSUE TITLE
Priorization Spring 2020

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1107]
## Features

* [ ] GCP Marketplace integration
* [x] Contextionary Memory Issues
  * [x] implementation & automated tests
  * [x] explorative tests by team members and community
* [x]  #1103 - Response on GET /
* [x] #1106 - Linkable references in REST
* [x] Parallelize Contextionary training process
* [x]  #1101 - Count references in where filters
  * released in 0.22.6
* [x] #1118 dynamic noise reduction POC
* [x] #1125 Implementation for results from #1118 into Weaviate
* [ ] #1116 
* [ ] #1098 - Neighbors of objects
* [ ]  #1085 - Explore based on objects
* [ ] Playground Bugfixes
* [ ]  #1089 - Search by phoneNumber
* [ ]  #1072 - Decision tree classifications

## Bug Priorities
* [ ] #1067 - Bug Index settings not visible
  * awaits feedback
* [x] #825 - Geo-Coordinates of 0,0
  * merged, but not released yet
* [ ] #929  - Misleading error message
  * needs investigation if still relevant
