### ISSUE TITLE
Link all Rest resources / resource groups on `GET /`

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1108]
This is the implementation following the discussion in #1103 

## Todos

* [x] define link schema
* [x] add root urls 
* [x] add documentation urls
* [x] if `ORIGIN` env is set use absolute links, if not use relative.
  * the config is currently still in files, not env vars, so probably best to put this config option in there as well
