### ISSUE TITLE
Information-Gain & TF-IDF support in Contextual classification

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1125]
This is the implementation for the POC findings of #1118, originally proposed in #1115.

## Todos

* [x] finalize design in POC (#1118)
* [x] extend current classifier so it can run preparation steps (required for tf-idf and caching of target objects)
* [x] extend parameters for new configuration (as designed in #1124)
  * [x] validate/set defaults
  * [x] use (safely) in classification to replace hard-coded values
* [x] extend interfaces (and repositories if required) with new db capabilites
  * [x] temporarily simulate `MultiVectorForWord` in c11y client
  * [x] implement actual `MultiVectorForWord` in c11y (https://github.com/semi-technologies/contextionary/issues/29)
* [x] aggregate information before run
  * [x] fetch target vectors
  * [x] calculate tf-idf score
* [x] update run
  * [x] calculate IG
  * [x] strip by IG and TF-IDF
  * [x] boost by IG if configured
* [x] fix/update broken/outdated/imprecise tests
  * [x] unit
  * [x] journey
* [x] check for unresolved TODOs in classification package
