### ISSUE TITLE
Switch DB mode based on config

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1144]
## Todos

* [x] Produce an empty shell that implements all the required interfaces
* [x] when a config flag is set, use new custom db mode
* [x] don't start up es in docker-compose
