### ISSUE TITLE
Custom DB MVP 1 - Save and Read simple Thing/Action

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1146]
## User Journey

A user can
* [x] import a Thing/Action schema that contains only `text` fields
* [x] import a Thing/Action with filled text fields
* [x] show the Thing/Action through the UI if they specify the exact UUID
* [x] show the Thing/Action as part of a list of all objects (i.e. object search)
* [x] show the Thing/Action in a GraphQL response (i.e. class search)

## Out of scope
* Inverted Indices
* Vector Indices
* Shards (Index==Shard at this level)

## Todos
* [x] Define index and shard types, add initializers
* [x] on init, get schema and create indices type
* [x] On class creation create one index
  * In the future this needs to be n shards, while not having to build that yet, we need to be aware of the target design so we don't obstruct the way
  * don't do anything field-specific yet, as we simply care about dumping the object at the moment, we only care about specific fields once we built the inverted index
* [x] on import dump with the literal UUID (covert to int?) 
* [x] on get-by-uuid retrieve
* [x] on object search dump within limit
* [x] on class search dump within limit
* [x] Make sure all hard-coded config is removed and set through config file
* [x] port existing (or create new) integration test to verify the features we already have
