### ISSUE TITLE
Custom DB MVP 2 - Datatypes and filters

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1147]
## User Journey

A user can 
* [x] import things with primitive data fields (`text`, `string`, `int`, `number`, `boolean`)
* [x] use a simple where filter for
  * text word match match
  * string exact match
  * number exact match
  * number larger than/smaller than
  * boolean exact match

## Tech notes

* We need to add a simple inverted index here, which has a bucket per datatype, so that we can make lookups
* This also requires the `uuid->index_id` translation

## Todos

* [x] on class creation
  * [x] add bucket for `indexID`
  * [x] add bucket for each (primitive) prop
* [x] index id
  * [x] design proper binary storage
  * [x] on import assign indexID, store with regular data
  * [x] on import add to indexID inverted index to quickly recover the UUID
* [x] on data import
  * [x] analyze props for words
  * [x] decide based on property type
  * [x] leave structure for tf-idf (does not need to be implement yet)
* [x] on search
  * [x] translate query to index look up
    * [x] `Equal`
      * on all props
    * [x] `GreaterThan`, `GreaterThanEqual`
      * on numerical props
    * [x] `LessThan`, `LessThanEqual`
      * on numerical props
  * [x] translate index ids to UUIDs, fetch objects
* support
  * [x] text props
  * [x] string props
  * [x] int props
  * [x] float props
  * [x] bool props
* [x] error as unsupported when search term has more than one word (text, string)

## Out of scope
* Geo-Type properties
* Reference properties
* Vector indices
* Nested Filters
* Tf Idf scoring
* Date props
* More than one word in search
