### ISSUE TITLE
Custom DB MVP 3 - Vector Search

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1148]
## User Journey

* [x] An entry that has a vector attached to it gets added to the HNSW index for this particular index/shard
* [x] A user can do a vector based search
  * across the entire db
  * across a particular class index
* [x] The index is persisted and loaded upon restart

## Todos

* [x] create index on shard creation
* [x] load from commit log if present
* [ ] switch and condense commit log periodically if criterium is matched
* [x] allow imporing default datasets (without refs so far)
  * [x] implement `Exists()`
* [ ] document limitations and allow tracking of progress on them
* [ ] unit test new code
* [ ] integration test replacement functionality

**Comment by etiennedi** [comment]
Ideally we don't start this until we know more about the distributability (#1164) of HNSW
