### ISSUE TITLE
Custom DB MVP 4 - All props and references

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1152]
## User Journey

* [ ] user can resolve nested references
* [x] user can resolve phoneNumbers, geoProps, etc.

## Tech Notes

We should be able to reuse the old schemaParser/referenceCacher, as a first step, we can make that a bit more generic (it's currently just methods on the old `esvector.Repo` type). 

## Todos
* [x] store and retrieve remaining props
  * [x] phoneNumber
  * [x] geoCoordinates
* [x] support single-level refs
  * [x] store refs as array in data object
  * [x] on parse resolve (if desired by the user)
* [ ] support nested refs
  * [x] Extract reference cacher to work with any repo
    * this in turn requires first abstracting multi-get into an actual repo method, so that the cacher no longer knows the repo internals
  * [x] Unit test previously untested code
  * [x] Build MultiGet Lookup
  * [x] Recursively resolve (using cacher) in `db` repo
    * since this is now happening at a relatively high level we need to make sure this runs for every possible entry point
    * [x] objectByID
    * [x] vectorClassSearch
  * [ ] Document Logic
  * [x] Add high-level tests (re-use old tests)
  
## Out of Scope
 * search by geoProps: TODO: what kind of an index do we need for this?
 * store refs in inverted index, filter by ref props
