### ISSUE TITLE
Add _classification results to GraphQL API

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1155]
It would be helpful if the [meta information](https://www.semi.technology/documentation/weaviate/current/classification/knn-classification.html#get-classification-meta-information-of-data-objects) after classification is part of GraphQL. This can be done as outline in #1136

## Todos

* [x] add `_classification` field in GraphQL with all it's sub-fields
* [x] populate new fields with content
* [x] in REST add `?include=classification,_classification` query params
* [x] in REST if meta prop is set, show deprecation warning
* [x] centralize deprecations in code
* [x] export deprecations in a format usable for the website
