### ISSUE TITLE
Add vectorization info in _interpretation property (in GraphQL and REST)

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1156]
It would be helpful if the actually parsed string is part of GraphQL's `__meta` function. So that it is understood what Weaviate used as the actual string to index (not only for classification but for indexation in general).

Can be implemented as part of #1136 

-- 
## Todos

* [x] extend contextionary (semi-technologies/contextionary#33)
* [x] extend REST API
* [x] extend GraphqQL API
* [x] store and retrieve with database
* [x] add journey test

**Comment by etiennedi** [comment]
Update: Switched from `_meta` to `_interpretation` since
* there was a conflict with the deprecated meta field (go-swagger internally removes the underscore, then they're called the same)
* it's less ambiguous and more descriptive
