### ISSUE TITLE
Add _semanticPath prop to REST/GraphQL

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1168]
Taken from #1136 which has grown too big. Original input by @bobvanluijt:

---

When Weaviate's semantic features are used to provide results to the end-user, we might be able to improve the UX to _why_ Weaviate came to these results by introducing a `__meta` "property" that contains additional information per class.

# Example API

A query might look like this (also includes the proposed values)

_Note: results function just as examples_

```graphql
{
  Get {
    Things {
      Article(
        explore: {
          concepts: ["beatles"]
        }
        limit: 1
      ) {
        title
        _semanticPath {
          path {
            concept
            distanceToQuery
            distanceToResult
            distanceToPrevious
            distanceToNext
          }
        }
      }
    }
  }
}
```

## Todos

* [x] finalize experiments and algorithm to determine meaningful path
* [x] extract into UC
* [x] run once per search item
* [x] add models
* [x] add to GraphQL API
* [x] add to traverser/explorer
* [x] calculate distances
* [x] add appropriate test coverage (how can we test this in a non-flaky fashion?)
* [x] replace go-tsne fork with original (the required PRs have been merged in the mean time)
