### ISSUE TITLE
Add _nearestNeighbors (related concepts) to both REST and GraphQL API

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1169]
## Todos

* [x] extend contextionary with `MultiNearestWordsByVector` (semitechnologies/contextionary#34)
* [x] extend local c11y client with `MultiNearestWordsByVector`
* [x] build neutral uc to extend list of search results with nearest neighbors
* [x] extend REST API
* [x] extend GraphQL API
* [x] add journey test (must not be too dependant on a specific c11y version)
* [x] replace tempoary links (contextionary branch version) with stable versions
* ~~find pragmatic solution regarding distances (numbers > 1 atm)~~
  * we have decided to accept the different distances for now
