### ISSUE TITLE
Add _featureProjection (optimized for visualization) to GraphQL and REST API

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1178]
## Todos

* [x] add to GraphQL API
* [x] build projector UC using `go-tsne` (We probably need to rely on a fork because the original is buggy and PRs haven't been merged yet)
* [x] add to REST API
  * [ ] allow setting parameters
* [ ] make all parameters configurable and choose reasonable defaults
* [ ] add journey test
