### ISSUE TITLE
Custom DB MVP 5 - Classifications

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1218]
## User Journey
* The user can run classifications up to 10,000 items
  * [x] kNN
  * [x] contextual

## Todos
* [x] Investigate what's currently keeping the user from doing so and fill todo list
* [x] Find unclassified (i.e. where ref==notset)
* [x] implement filter by refcount
  * [x] for each refprop, add a `count` bucket
  * [x] set count when refs are present
  * [x] figure out when a ref is not present to explicitly set it for `0`. (compare possible schema to set schema)
  * [x] write filter logic for `int` / `refProp`
* [ ] ~~Refactor GetUnclassified to use refCount filter~~ scoped out
* [x] make sure objects can be updated (using `db.Put{Kind}`)
   * [x] object itself
   * [x] adding onto inverted indices (do not add if already present)
    * ~~updating inverted indices~~ scoped out to #1221 
    * ~~updating vector indeices~~ scoped out to #1221 
* [x] allow contextual
  * requires `GetUnclassified`
* [x] allow knn
  * [x] combine vector & structured searches (knn requires bool filter + vector search, as knn candidates are the closest items with the matching refs set)
  * [x] test exploratively
  * [x] test automatically
* [x] fix issues coming up in explorative testing and benchmarking
  * [x] parallelize classification runs
  * ~~batch update classification results or handle errors of individual approach~~ concurrent updates removed again, a longterm solution scoped out to #1219
  * [x] write checksum for inverted index row
  * [x] implement cacher for inverted index rows
  * [x] read inverted index row from cache if checksum hasn't changed
  * [x] skip inverted index row merging if checksum of to-be-merged are identical
  * [x] batch putObjects
    * [x] implementation
    * [x] tests
  * [ ] update limitations document
  
 

## Out of scope
* Normal filter capability restrictions apply, i.e. if filtering is not completely supported when implementing this (e.g. missing fiter by ref), then it won't be added here either unless necessary to achieve the goal
* removing from inverted indices
