### ISSUE TITLE
Custom DB MVP 6 - Increase "per shard" limits

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1219]
## Goal 

* Users can import medium sized datasets (single-shard)

## Todos

* [x] make HNSW index growable
* [x] peridocially switch and compact commit log
  * [x] replace single file commit log with folder
  * [x] write into newest timestamp
  * [x] read all from oldest to latest
  * [x] periodically check - on write - if file needs to be switched
  * [x] periodically (separate go-routine) see if there are uncondensed commit logs, condense them from old to new
  * ~~on startup if last commit log is X% full, start new one~~ outscoped to #1260
  * [ ] replace prints with structued logging
  * ~~add sanity check if both raw and uncondensed exist at startup. This can only mean the previous condensing was interrupted~~ outscoped to #1260
* ~~store classification in batches~~ outscoped to #1261
* ~~handle commit log write error~~ outscoped to #1260
* [x] investigate and fix scaling issues
  * [x] imports become slower
     An overnight benchmark on September 22 has shown that imports gradually get slower at larger scale to the point that we've seen unexpected timeouts. 
  * [x] fix ineffecient `append`/`copy` statementes in inverted index builder. Import time is now pretty much linear again 
  * [x] fix vector cache clean up
    * concurrent deletes weren't fast enough while importing, so new writes led to a never-ending circle of deletes. Instead there is now an `RWMutex`, that uses `RLocks` for normal operations (read and write, as the `sync.Map` is already capable of concurrent read/write without a lock) and only uses the `Lock` for deletes. The delete is a simple replacement of the `sync.Map`. 
* [x] use better defaults for query-time `ef` values. It currently breaks on very large values. 

## Out of scope
* Multi-sharding
* Replication
