### ISSUE TITLE
Custom DB Full CRUD operations

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1221]
Adding onto an inverted index is easy, but updating or deleting is considerably more complicated:

## Goals

* [x] delete
  * [x] removes the object itself (uuid query returns 404)
  * [x] removes all inverted indices pointers (searches exclude it and are cleaned up)
  * [x] removes from the vector index
* [x] update
  * [x] updates the object itself
  * [x] updates the inverted indices
  * [x] reindexes the object if the vector position changes (wouldn't change on e.g. a ref-update)
* [x] merge
* [x] add ref
* [x] batch add ref

## Todos

* [x] objects
  * [x] add delete
* [x] inverted index
  * [x] add delete capability (run analyzer on last state and remove pointers)
  * [x] on update, calculate delta
    * [x] no action on entries which stay
    * [x] only add to be added
    * [x] only clean up to be cleaned
    * [x] if vector changes increase doc ID and clean up (should we always do this?)
* [x] hnsw
  * [x] add ability to delete (is there a smart way to clean up?)
    * [x] brute force delete
    * [x] allow deletion of entrypoint
    * [x] mark deleted with tombstone, which is ignored on search
    * [x] periodically clean up tombstones through batched brute-force delete
    * [x] support persistence in tombstoning
    * [x] support persistence in edge reassignment
  * [x] on update if vector changed run both delete as well as new insert on update
* [x] merge
* [x] add ref
* [x] batch add ref

**Comment by bobvanluijt** [comment]
![https://memegenerator.net/img/instances/47021946.jpg](https://memegenerator.net/img/instances/47021946.jpg)
