### ISSUE TITLE
September 15 Checklist

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1236]
* [x] Remove "broken" endpoints (#1235)
* [x] Support CRUD capabilities in Standalone Mode (#1221)
* [x] Draft Architecture page for website/docs
* [x] deprecate config file, allow env config (#1230)
* [x] Clean up Standalone Mode "not implemented" error messages or panics
* [x] verify auto-generated configs e2e
* [x] remove hard-coded docker-compse files, replace with links to docs
* [x] update release notes script to use configruation API
* [x] Javascript client
  * [x] implement and publish preview semi-technologies/weaviate-javascript-client#5
  * [x] fix issues based on feedback
  * [x] publish as `1.0.0`
* ~~(if possible in time) remove cardinality #1142~~ scoped out

**Comment by etiennedi** [comment]
Closing as complete, scoped out things are moved to #1241
