### ISSUE TITLE
Deprecate Cardinality in schema reference props

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1240]
## Goals
* [ ] Refs always behave as they currently do with `many`
* [ ] Classifications still work e2e, edge cases are caught 

## Todos
* [ ] Add deprecation notice if property is set
* [ ] Add deprecation to `swagger.json`
* [ ] Remove all checks
* [ ] Identify and remove behavior that depends on cardinality
* [ ] Remove schema check in classifications, instead check reference count at runtime
  * AFAIK there are places where assume that refs must have length one, etc. 
* [ ] Exploratively verify everything still works
