### ISSUE TITLE
Standalone Geo Spatial Index

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1249]
depending on the results of #1248

## Todos

* [x] support per-property vector index
* [x] create vector index for each geoProp
  * [x] on create
  * [x] on restore
* [x] on import 
  * [x] write into index
    * [x] on regular put
    * [x] on batch put
* on update
  * basically undefined behavior due to #1272  - maybe scope out? -> scoped out to #1281 
* [x] provide geoCoordinatesFromDocID method (equivalent for vector For ID)
* [x] on search
  * [x] search geo index as part of inverted
  * [x] cut off by distance instead of amount
* ~~(optional) make cache sizes configurable~~
