### ISSUE TITLE
Make docID uint64 (currently uint32) - to enable imports larger than 4M per class

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1282]
## Background

Originally, the assumption was that indices would always be made up of many shards, so a small limit (around 4M) per shard would be sufficient. However, since then there have been the following developments

1. DocIDs will become immutable as outlined in #1272, meaning the effective capacity of one shard would be considerably smaller than 4M, as 4M could be reached if all imports were pure imports, but no upserts
2. The indices used (inverted, HNSW, etc.) perform well reasonably well also at larger capacity, so there is no need to limit the size of a shard. If not for other motivations (e.g. HA in a distributed setup), we expect use cases to be fine with 10M or 100M single-shard setups

## Todos

* [x] in all storage (document storage, inverted index, helper indices) change uint32 to uint64 for Doc ID
* [x] in all vector indices (currently only HNSW) consistently use uint64 for Doc ID
* [x] clean up all situations (assumption is that this only applies to HNSW) where Doc IDs are currently using untyped `int` or signed `int32` to consistently use `uint64`
* [x] fix issue where `docID` is prefixed with 4 empty bytes, see notes

## Process
This issue should probably be coordinated with the implementation of #1272, they will probably touch on very similar areas. So if they can happen in sequence as opposed to parallel, we will probably avoid plenty of merge conflicts.

## Notes

* There is an issue where we accidentally prefix the docID with 4 empty bytes. Ironically we haven't found this until now because we consistently do it when [reading](https://github.com/semi-technologies/weaviate/blob/32017f2eb5776449d439d5fde587a4b9db8f01fe/adapters/repos/db/shard_read.go#L124-L126) and [writing](https://github.com/semi-technologies/weaviate/blob/32017f2eb5776449d439d5fde587a4b9db8f01fe/adapters/repos/db/docid/docid.go#L40-L42). (There may be other places which are affected!)
