### ISSUE TITLE
Don't assign new doc id when udpate requires no clean up and vector position is unchanged

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1334]
## Background

* We have decided that updates to the inverted index will replace the entire object, so that deletes can happen async
* Currently we always do that strategy, even if the update would not lead to any deletes on the inverted index
* As a side-effect adding (only) a ref requires a full-reindex of the object, including a reindex in the vector index. This makes batch-ref imports much slower than they could be

## Todos

* [x] re-use docid to save vector index update
* [x] make sure ref count index updates are reflected
* [ ] group inverted deltas for more efficient writing
* [ ] make sure search by ref still works

## Idea

Whenever we are sure that an update would not lead to an altered vector position and would not require deletions of the inverted index, we could treat it as an "extend only" and not alter the doc id. This should make batch ref imports considerably faster.

**Comment by etiennedi** [comment]
Similarly to the above classifications are currently slowed down by their updates as well. The potential fix mentioned above might also work for classifications, since they are also an "extend-only" operation. The only thing we write in classifications are the new cross-ref and the classification meta info. Neither of which would require cleanup in the inverted index or reindexing in the vector index, so we could skip them both.

**Comment by etiennedi** [comment]
Adding @michaverhagen and @laura-ham as stakeholders for this.
