### ISSUE TITLE
text2vec-transformers modules MVP 1

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1459]
## In scope
* [x] vectorize at import time
* ~~vectorize at search time (waiting for #1436)~~ outscoped to #1473

## out of scope
* vectorization/index configuration
* movements
* additional properties
* REST extensions

## Todos
* [x] build simple inference container
* [x] build client to connect to inference container
* [x] provide `Vectorizer` module capability with client
* [x] add basic configuration (vectorize, skip)
* [x] add specific configuration (pooling method)
* [x] check for inference container to be present at startup
