### ISSUE TITLE
LSM-Tree Storage

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1523]
## Background

In one of our recent larger-scale demos with Wikipedia paragraphs, we have noticed that import performance degrades over time. The first 100k objects are reasonably fast, the next 100k are a bit slower and by the time 1M has passed we saw less than 50% of the initial performance. The culprit is the object and inverted storage, which currently uses bbolt and is therefore based on a B+tree approach. Writing into the vector index also gets a bit slower over time, however that is roughly `O(log n)` and seems to plateau relatively quickly. We can clearly see that bbolt commits are the bottleneck at the moment.

Initially, the focus was only on read performance - which is great at the moment. However, we're now realizing that even the best read performance isn't worth too much if importing becomes such a bottleneck that you can't practically get to very large datasets.

## Goal

Rather than putting in another workaround for the B+tree approach, we want to now investigate LSM-trees which are far more suitable for high-performance writing. Goal of this POC is to prove that an

* an LSM-based approach actually solves our problems
* get an understanding of how big of a change this is

### Update to the Goal

We have since moved past the POC stage. The approach is promising enough to provide exactly what we need. This issue is now no longer about trying to prove a technique, it's about implementing it

### Tasks

* [x] build simple memtable which orders data
* [x] write into write ahead log in memtable
* [x] support orderly shutdown with wait-for-flush
* ~recover from commit log if present at startup~ outscoped to #1570
* [x] periodically flush to disk segment when thresholds are crossed
* [x] on write, always write into mem table
* [x] on read, first check mem table, then check disk segments
* [x] use bloom filters to skip unnecessary segments on read
* [x] support multiple read strategies, such as 
  * [x] return latest (required for the object storage)
  * [x] return collection (required for the inverted index rows)
    * [x] memtable append
    * [x] disk segment append
    * [x] memtable remove
    * [x] disk segment remove
    * ~~reflect in commit log~~ outscoped to #1570
 * [x] support update (replace)
 * [x] support delete through tombstone
 * ~~periodically merge segments of the lowest levels~~ outscoped to #1570
 * [x] support range queries (could be a primitive approach for now, which loads all in mem, resorts and returns. In the future it could be a more elaborate approach that iterates over each segment, similar to a merge sort)
 * ~~support multiple primary ids per bucket. This way we could save the `docId to UUID bucket`. However, this could also be more of an optimization later one, we could keep the bucket in the short run.~~ outscoped to #1570 
 * [x] group multiple buckets in a wrapper type which handles all filesystem interaction
