### ISSUE TITLE
Replace bolt with LSM approach

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1569]
In #1523 we have built an LSM storage system. This ticket is about replacing bolt with the LSM approach. For a smooth migration, we can add the LSM storage alongside the bolt storage and duplicate all writes. Then we can slowly start transitioning the reads from one storage mechanism to the other. 

## Todos

* [x] write into object storage
  * [x] single
  * [x] batch
  * [x] merge
* [x] write into inverted storage
  * [x] single
  * [x] batch
  * [x] merge
* [x] delete form inverted index
* [x] consume inverted storage
* [x] adapt aggregate
* [x] make sure all buckets are initialized after restart

## Cleanups
* [x] make sure all buffered commit loggers are flushed at the end of a batch or single request
  * [x] hnsw
  * [x] LSM

## Related
See also #1570 for other changes which need to be performed before this can be released.
