### ISSUE TITLE
Add shard-configuration to config

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1599]
* Defaults to one shard per index, can be more than one
* If multiple are selected, multiple shards are created (at this point we can still always write in the first shard)

## Todo
* [x] Design and implement config
* [x] Validate mutable/immutable fields
* [x] Build config into schema manager
* [x] Design `State` component
* [x] Add marshalling/unmarshalling components to `State`
* [x] Store state with schema manager 
* ~~Gracefully migrate `"single"` shard into new system if present~~ outscoped to #1622
* [x] In `repos.DB` prevent startup if more than one shard is present (outscoped to next issue)

**Comment by etiennedi** [comment]
Complete, but keep open until merged.
