### ISSUE TITLE
Forward import to non-local shard, query across nodes

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1658]
## Todos

* [x] import individually
* [ ] `Exists()` check
* [x] import in batches
* [x] import references in batches
* [x] Get object by ID
* [x] Get object list
* [x] Non-vector Search  
* [x] Vector-Search
* [x] Multi-Get and resolve references
