### ISSUE TITLE
Meetup September 30th checklist

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1695]
## Todos

* [ ] make rc-release
* [ ] finish cluster/scaling documentation
  * [x] content
  * [ ] release
* [ ] prepare demo case
  * [x] kubernetes cluster
  * [ ] demo datasets for importing
* [ ] clients releases or rcs
  * [x] python
  * [ ] js
  * [ ] java
  * [ ] go
* [ ] slides 
* [x] fix desired/actual count
* [ ] release helm chart (rc)
