### ISSUE TITLE
Shard/Index introduce versioning

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1833]
* Anything that did not have versioning before is read as `1`
* Anything that is written with the new index is stored as `2`
* Future index changes will increase the number further
* This way we can fall back to old mechanisms if there was a breaking change (such as switching doc ids from `LittleEndian` to `BigEndian`)
* When version is `1` keep writing and reading with little endian in all places, if version is at least `2` use big endian

## TODOs
* [x] initialize version on shard startup
  * if no file exists and no data is present -> latest version
  * if no file exists and data is present -> assume `v1`
  * in all other cases read version from disk
* [x] error if trying to use BM25 before `v2`
* [x] use `LittleEndian` for `v1`, `BigEndian` for `v2` when reading and writing doc ids in inverted index
* [x] if `v1` sort rows in `MapList`
* [x] if `v1` sort rows in map cursor
* [x] if `v1` sort rows in map compaction

**Comment by etiennedi** [comment]
To find some of the affected places grep for `TODO gh-1833`

**Comment by etiennedi** [comment]
This is complete and can be closed :-)
