### ISSUE TITLE
Improve Contributor (technical) docs

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#724]
This is a reminder to myself so put down some contributor facing docs about some concepts that might be explained well in the code, but not from bird's eye view in the contributor docs

## General Topics
- [ ] Distributed Locking: Why and How
  - [ ] Also explain that a (non-batch) `CreateThing/Action` can be a schema-modifying query because of the Network-Cross-Ref feature
- [ ] Caching strategies around OLAP queries (this also has a User facing component), both can be tackled as part of #719 and #720 
- [ ] Best practices and architectural ideas around the `graphqlapi` package and it's subpackages
- [ ] Update Code style, etc. in general contributor docs

## Connector Specific Topics
@bobvanluijt where should we put connector-specific docs? They are only relevant for people wanting to contribute to existing connectors (rather than build a new one) or want to build a new one that is extremely similar and want to understand how existing connectors deal with individual problems, so they have an idea for other connectors.
- [ ] Janus: Outline best practices and highlight areas that need urgent improvement (e.g. #612)
- [ ] Janus: Explain how the general caching strategy (from above) is implemented by the Janus connector (related to #719 and #720) - currently awaiting external input.
- [ ] Janus: Batch importing strategy

**Comment by etiennedi** [comment]
@bobvanluijt One suggestion to my question above: Create a new `docs` subfolder in the specific connector with it's own `index.md`. Link that one from the overall contributor docs index page.

**Comment by bobvanluijt** [comment]
Hi @etiennedi, I would prefer to keep everything in the docs folder. In this case it would be the contribute sub-folder.

**Comment by etiennedi** [comment]
Also fine with me, in this case I'll just create a `janusgraph` sub-folder in the existing `contribute` subfolder. :)

**Comment by etiennedi** [comment]
Keeping it open as the general idea is still relevant. Needless to say everything around "Connectors" is obsolete, however the distributed locking part is still relevant as of now (Even though I'm also aiming to get rid of it, as locking is often a bottelneck in importing).
