### ISSUE TITLE
update to contextionary with occurrence

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#849]
This is a breaking change, depending on a new release of the updated contextionary.

## Todos

* [x] accept occurrence in c11y functions
* [x] take stopwords file from config
  * [x] parse
  * [x] validate presence
* [x] update validation rules for stopwords
  * [x] add test cases and make them pass
  * [x] use in non-test scenario
* [x] strip out stopwords when building centroids
* [x] update docs about stop words
* [x] remove stop words from dev c11y
* ~~add acceptance tests around stop words~~
  * no need, we already have existing schema objects using a mix of stop-words and non-stop words
* [x] in production image add stopword list alongside c11y (will be removed once we extract c11y)
* [x] reflect breaking changes in Helm chart

**Comment by etiennedi** [comment]
Closing as complete.
