### ISSUE TITLE
Minimal "Admin or nothing" authorization

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#876]
In the spirit of pluggable authorization techniques, this should be the first step to provide any kind of Authorization that can be combined with the existing OIDC Authentication plugin. In the future more fine-grained authorization will be possible using RBAC as outlined in #802. 

## Goals
* a list of user ids (or emails) can be provided at config time
* each member of the list will have all API capabilities
* a non-member will have no API capabilities
* health checks should not be protected

## Todos
* [x] extend config with option to include `adminlist` authorization technique
  * [x] if not set, same behavior as before
  * [x] if set, plugin is activated
* [x] each API-exposed UC will call the authorizer with a minimal description of what there is to do, principle can be included in the context
  * [x] in REST
    * [x] start with one example UC
    * [x] update all UCs
      * [x] kinds
      * [x] batch kinds
      * [x] schema
      * [x] others
  * [x] in GQL 
* [x] if there is a match, the request is allowed as planned
* [x] it there is no match, the request is denied
  * [x] make sure all API endpoints allow a 403
  * [x] use structured error to propagate
  * [x] catch forbidden error in handlers and return 403
* [ ] make sure it works with Kubernetes setup
  * [ ] update helm chart
  * [ ] release updated version
* [x] update docs
