### ISSUE TITLE
Add explore "ranker" to Local Get GQL Search

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#881]
## Goals

* when `explore` ranker is set
  * [x] search with vector index rather than connector
  * [x] retrieve whole class per ID from connector backend
* [x] when `explore` is not set, behavior is as it used to be
* [x] when `explore` and `where` is set at the same time, error for now (will be solved in #911 )

## Todos
* [x] extract explore argument from gql api into uc args
* [x] in `esvector.Repo` allow search limited to single class
* [ ] build new `explorer` uc in `kinds` package
  * [x] in explorer if both `explore` and `where` args are set, error. (This will become possible with #911)
  * [x] otherwise perform vector search only for class
  * [ ] for each resolve, retrieve class by ID (can we make this more effecient?)
* [x] in `Traverser.LocalGet` 
  * if `explore` arg is set, resolve with explorer
  * else resolve "traditionally"
* [ ] manual verification
* [ ] e2e test

## Out of scope
* #911 Where filters
* #912 Cross-refs

Suggestion: with the new c11y features, an option to search by context becomes possible.

```graphql
{
  Local {
    Get {
      Things {
        Review(explore: {
                concepts: ["GTA", "5", "reviews"],
                moveTo: {
                  concepts: ["positive"],
                  force: 0.5
                },
                moveAwayFrom: {
                  concepts: ["epic"],
                  force: 0.25
                },
        			}) {
          name
          ofGame{
            ... on Game {
              name
            }
          }
        }
      }
    }
  }
}
```

Expected result:

```json
{
    "data": {
        "Local": {
            "Get": {
                "Things": {
                    "Review": [
                        {
                            "name": "Alice",
                            "ofGame": {
                               "name": "GTA"
                            }
                        }
                    ]
                }
            }
        }
    }
}
```

**Comment by bobvanluijt** [comment]
Updated based on: https://github.com/semi-technologies/weaviate/issues/883

**Comment by etiennedi** [comment]
@bobvanluijt Do we still need this if we implement #896? Both an explore filter and and explore operator among the regular where filters might be a bit confusing from a UX perspective?

**Comment by bobvanluijt** [comment]
Yeah, that’s a fair point.

Can we combine them into a single one which takes the best of both suggestions? I assume you have some ideas from a pragmatic implementation PoV.

**Comment by etiennedi** [comment]
> I assume you have some ideas from a pragmatic implementation PoV.
Not yet, but this is what I'm moving onto next. I'm closing this issue so we can have all related discussions in #896. I'll also try to compare them to each other to make sure we also include the best parts of this suggestion.

**Comment by etiennedi** [comment]
Update: Reopening this, until we have aligned. Might make sense to merge #896 into here rather than the other way around.
