### ISSUE TITLE
Minimal vector based concept search

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#888]
## Goal 
An early as possible pre-release

## Limitations to speed up delivery
* no indexing of props, i.e. only Explore->Concepts search, but without structured filters
* a single index, no separate indices per Class/etc.
* occurence not reflected, only stopwords removed

## Todos

* [x] Include required ES with vector plugin in stack
* [x] build vectorizer to be used at import time
  * [x] translate class instance to corpus
    * [x] only use string props in MVP pre-release
  * [x] use at import time
    * [x] concept to vector
    * [x] import to vector repo
* [x] adapt contextionary
  * [x] return single centroid for class corpus text
  * [x] remove stopwords or words not in the c11y
  * [x] error if no words left
  * [x] build client in weaviate
* [x] build vector repo
  * [x] prepare schema once - how? when?
    * [x] build idempotent way to manage schema
    * [x] run for example at startup. In the future we need to run this as part of the schema manager as it depends on the schema. But for now there is just a single index, so we can just run it once
  * [x] import single entry
  * [x] perform search, return list of IDs
* [x] replace Fetch Fuzzy with Explore Concepts
  * [ ] (optional) renamings and new features from #883 
  * [x] send off vector search, ~~for each ID get result from Janus~~
