### ISSUE TITLE
Suggestion: Give user ability to set UUIDs

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#903]
## Todos

* non-batch
  * [x] add missing unit tests for AddThing/AddAction UC to be able to safely make changes  
  * [x] if user sets valid uuid, don't assign new one
  * [x] if user sets no uuid, assign automatically
  * [x] if user sets invalid uuid, error
  * [x] if user sets existing uuid, error
* batch
  * [x] add missing unit tests for AddThingBatch/AddActionBatch UC to be able to safely make changes  
  * [x] if user sets valid uuid, don't assign new one
  * [x] if user sets no uuid, assign automatically
  * [x] if user sets invalid uuid, error
  * [x] document that no alreadyexists validation is happening on batch

## Proposal

Currently importing things that depend on one another (i.e. cross-references) is hard, because we need to:

1. Import ThingA
2. Catch the ID of ThingA
3. Modify the payload of ThingB to include a beacon with a reference to Thing A
4. Import ThingB

If we allowed the user to set the UUID on Thing A, they could just assign UUIDs as they please and then import ThingA and ThingB without having to either catch an ID or modify a payload.

@bobvanluijt Thoughts?

**Comment by bobvanluijt** [comment]
Yes! This would be fantastic. I would allow all UUID versions (if possible) except for Nil UUID types.

**Comment by bobvanluijt** [comment]
I would like to move this up if possible, it comes in handy for some use cases.

**Comment by etiennedi** [comment]
Sure, what do you offer in return? 😛 

Kidding. In all seriousness, sure. I don't think I'll get to it today, but I can still prfioritize this highly.
