### ISSUE TITLE
Index Concepts per Class in Vector Index

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#905]
In #888 we built a simplified vector index which would store each class instance in a single index. This was enough for generic `Explore` (formerly `Explore { Concepts }`), but isn't sufficient to combine structured filters with vector based searches

This is a requirement to be able to build #881.

## Goals

* [x] when adding a schema class, create an index (with the correct mappings) in the vector backend
* [x] when updating a schema class, update the existing index
* [x] when deleting a schema class, delete the index
* [x] when inserting a class instance, insert into the correct index, fill all primitive subfields
* [x] when performing an `Explore` search, search across all indices

## Todos
* [x] build migrate composer
* [x] rename unnecessarily verbose types, such as `SemanticSchemaClassProperty -> Property`
* [x] implement `migrate.Migrator` interface with `esvector`
  * [x] addClass
  * [x] dropClass
  * [x] addProperty
  * [x] dropProperty
  * [x] unsupported:
    * [x] update property
    * [x] update class
    * [x] update property add data type
* [x] update inserts to contain all required fields
* [x] udpate search to search across indices
* [x] remove any global indices introduced in #888 as a temporary solution
* [x] check for remainign todos created in #888
