### ISSUE TITLE
Vector based Searching Overview

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#907]
This is an umbrella issue to group all issues related to vector based searching

* [x] #888 Minimal Vector based search ("Explore Concepts")
* [x] #883 Explore{} functionality
* [x] #906 Add `explore` ranking to GQL `Local Get`
* [x] #904 Improve GQL API of "Explore"
* [x] #905 Index per class
* [x] #881 Resolve `explore` ranking in GQL `Local Get`
* [x] #916 Delete vectors
* [x] #917 Add certainty to explore
* [x] #908 Turn feature on/off **<-- all above released as 0.17.0**
* [x] #911 Combine `where` filter with `explore` ranker **<-- all above released as 0.18.1**
* [x] #912 Resolve Cross-Refs when `explore` argument is set
* [ ] #910 write vector on update, delete kind, etc.
* [ ] ...plenty more coming soon

**Comment by bobvanluijt** [comment]
+1 for the `...plenty more coming soon` :-P

**Comment by etiennedi** [comment]
Closing as complete.
