### ISSUE TITLE
Add ability to turn vector search on/off completely

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#908]
Existing use cases might not necessarily need the vector search, however the vector concept search needs additional backends. If it was "always on", all exiting users would have to upgrade their stack even if they aren't using the feature.

## Implementation Ideas
This might be elegantly done by implementing a noop-esvector backend. Instead of hundreds of if switches, the entire backend is switched and the backend does nothing except maybe debug logging that it would now do something if it wasn't turned off.

## Todos

* [ ] Don't do anything related to vectors if feature is turned off
* [ ] show correct error in APIs
* [ ] when vector search is off make sure that unsupported features are blocked (e.g. extend composer with capabilities)
