### ISSUE TITLE
Allow combination of "explore" and "where" rankers/filters in Local Get

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#911]
depends on #881 to be complete

## Todos
* Validate in UC
  * decided to take no further action after manually validating that the possible combinations lead to intuitive results, including empty results for non-sensical queries, such as `City.name <= 200`
* [x] Primitive Filters
  * [x] string
     * [x] eq
     * [x] neq
  * [x] text
     * [x] eq
     * [x] neq
  * [x] date
    * [x] as number
  * [x] number
    * [x] eq
    * [x] neq
    * [x] gt
    * [x] gte
    * [x] lt
    * [x] lte
  * [x] int
    * [x] as number
  * [x] geoCoordinates
* [x] edge cases, such as email vs. full text match
  * [x] text vs string field
  * [x] email contained in text field
* [x] Chain primitive filters
* ~~Cros-refs~~ will be added once there is general esvector cross-ref support
