### ISSUE TITLE
Add certainty to Explore function

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#917]
With the same behavior as `certainty` with beacons.

```graphql
{
  Local{
    Get{
      Things{
        Book(explore:{
          concepts: ["derek", "hartfield"],
          certainty: 0.9 # <== here
        }){
          title
          HasAuthors{
            ... on Author{
              name
            }
          }
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
## Todos

* [ ] add certainty to GQL arguments
  * [ ] Local Get
  * [ ] Local Explore
  * [ ] defaults to 1 if not set
* [ ] calculate distance/certainty for results
  * [ ] in Explore, turn distance to certainty (1-distance)
  * [ ] in Local Get add
  * [ ] omit entries if certainty < required
    * [ ] in Local Get
    * [ ] in Expore

**Comment by etiennedi** [comment]
@bobvanluijt  Feature is available in this pre-release: https://github.com/semi-technologies/weaviate/blob/4105ac740bf99aa53088fde8ab6561fda23cecc1/docker-compose/runtime/docker-compose.yml#L10

**Comment by bobvanluijt** [comment]
check, thanks, works like sunshine
