### ISSUE TITLE
Proposal: remove Local{} and Network{} & only allow Network beacon search

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#925]
# Current situation

```graphql
{
  Local{
    Aggregate{}
    Get{}
    GetMeta{}
    Explore{}
  }
  Network{}
}
```

# Proposal

```graphql
{
  Local{ # <== remove
    Aggregate{}
    Get{}
    GetMeta{}
    Explore{}
    Fetch{}  # <== remove (has this still a function?)
  }
  Network{}  # <== remove
}
```

New structure:

```graphql
{
    Aggregate{}
    Get{}
    GetMeta{}
    Explore{}
}
```

# P2P requests

```graphql
{
    Explore(concepts: ["banking"], networkExploration: true) {
      beacon
      certainty
      className
  }
}
```

Potential results:

```js
{
    "data": {
        "Network": {
            "Explore": [
                {
                    "beacon": "weaviate://localhost/things/742...28bd",
                    "certainty": 0.8000992,
                    "className": "Company"
                },
                {
                    "beacon": "weaviate://peer002.semi.network/things/f20f...225",
                    "certainty": 0.786739,
                    "className": "Business"
                }
            ]
        }
    }
}
```

**Comment by etiennedi** [comment]
## Todos

* [ ] remove `Local` / `Network` wrapper
* [ ] remove `Network` GQL API 
* [ ] remove `Fetch`
* [ ] add `network` option to `Explore`

**Comment by etiennedi** [comment]
@bobvanluijt 

I made one minor change to the above. `networkExploration` is simply called `network`, as it's already in the context of `Explore`, so I removed the stuttering.

Feel free to check out the pre-release: `semitechnologies/weaviate:0.18.0-afa396b`. If you're happy with it, I can turn it into an actual release.

**Comment by bobvanluijt** [comment]
Validated and 👍
