### ISSUE TITLE
Roadmap 0.20.0: Remove Janusgraph, replace with esvector

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#932]
## Roadmap
* [x] #942 Add feature toggle to completely remove Janus early on
* [x] #943 Serve `Get` solely with `esvector` if `explore` is set, leave with Janus when no explore is set so that cross-refs still function
* [x] #945 Serve CRUD capabilities (no cross-refs) from ES
* [x] #941 Replace Aggregate 
* [x] Replace Meta or Merge with Aggregate, see #949 
* [x] #954 support cross-refs
* [x] #962 Filter by cross-ref
* [x] #963 update stale cross-ref cache
* [ ] address flakiness in integration tests (two tests suits try to turn caching on and off, sometimes they interfere)
---
### Clean ups
* [x] remove schema composing
* [x] remove importing
* [x] remove connector logic
* [x] remove leftovers

## Pre-Release checks
* [x] run all e2e tests with new stack
* [ ] verify playground works
* [ ] manual verificiation with real life use cases

## Release Notes

* Breaking
  * base unit for geo search is meter not kilometer
  * text/string difference
  * no aggregations on text props
* Known limitation
  * filter by cross-ref only within cache boundary, see #967 
  * deleting properties #973
  * aggregration string prop count not working
* Usage guidelines
  * Eventual consistency
  * Avoid supernodes
  * Adjust cache denormalization depth if necessary
