### ISSUE TITLE
API breaking changes for 0.19.0

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#934]
As part of the new release 0.19.0 we want to group a lot of breaking changes in our API, so that we can then stay stable for a long time after that.

## Todos

* [ ] `/meta` does not return schema
* [ ] `/meta` should display 
  * [ ] version number
  * [ ] c11y version number
  * [ ] (optional p2p info)
  * [ ] number of words in contextionary
* [ ] ref can either be beacon type or fuzzy type
  * [ ] fuzzy type will fail with not supported yet
* [ ] in GQL `...on Beacon` reference is available
  * [ ] no implementation yet
* [ ] in cross-ref creation `$cref` becomes `beacon`
* [ ] API base `weaviate/v1` becomes just `v1`
* [ ] in GQL `GetMeta` renamed to `Meta`
