### ISSUE TITLE
Serve Aggregate UC from esvector

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#941]
## Todos

* [x] support single prop, single agg
* [x] support singple prop, mutli agg
  * [x] regular numerical
  * [x] mode
  * [x] median
  * [x] count
* [x] multi prop, multi agg
* ~~non-numerical types~~ nothing to do here, they only support count anyways
* [x] refactor gql to use proper types
* [x] enable in UC
* [x] sort groups by count DESC
* [x] fix odd behavior
  * [x] `key_as_string` error when aggregating non-numerical
  * ~~boolean true/false vs 0/1~~ not fixing now, as there would be substantial effort involved and we're not sure if the behavior is even a problem
