### ISSUE TITLE
Add feature toggle to remove Janus stack

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#942]
It will take a certain amount of time (ETA 6 to 8 weeks) until the Janus stack has been replaced by the new esvector features.

We cannot fully remove the janus stack yet, as we'd lose functionality. Instead we want to add a feature toggle, which - if set - ignores Janus. When the toggle is set, not all features will be available until they have been replaced.

## Todos 

* When toggle is set
  * [x] remove startup routine
  * [x] remove Janus from migrator composer
  * [x] remove Janus from importing vertices
  * [x] fail APIs
    * [x] Get
    * [x] Meta
    * [x] Aggregate
    * [x] REST API
