### ISSUE TITLE
Serve traveser.Get with esvector (without dependency to Janus)

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#943]
Limitation: no cross refs for now

## Todos
* [x] add schema returns to esvector repo
* [x] add ability to search without vector (`ClassSearch`)
* when explore is used
  * [x] serve soleley through esvector
* when no explore is used
  * and esvector feature flag is off
    * [x] serve traditionally with janus
  * and esvector feature flag is on
    * [x] serve through esvector
