### ISSUE TITLE
Add CRUD capabilities to esvector backend

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#945]
## Limitations

No support for cross-refs

## Todos

* Add already present from #888 
* [x] Update (should be close to Add, since esvector has idempotent Put)
* Delete already present from #916 
* [x] Get (List) (no filtering)
* [x] Get Single (filtered by ID)
* [x] contain all metadata (created, lastedited) in Get responses
  * [x] write on create
  * [x] read in all searches
