### ISSUE TITLE
Proposal: Remove Meta {}, merge into Aggregate {}

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#949]
The GQL APIs for Meta and Aggregate are extremely similar. For example:

**Meta**
```graphql
{
  Meta {
    Things {
      City {
        population {
          maximum
          count
          minimum
          sum
        }
    }
  }
}
```

**Aggregate**
```graphql
{
  Aggregate {
    Things {
      City(groupBy: ["name"]) {
        population {
          maximum
          count
          minimum
          sum
        }
      }
    }
  }
}
```

## How do they differ?
* `Meta` take the entire dataset, `Aggregate` groups (currently mandatory)
* `Meta` can show `topOccurences` for strings, `Aggregate` can only show count

## Proposal to not lose functionality, but simplify API
* Add `topOccurrences` to `Aggregate` string props
* When `groupBy` is set `Aggregate` behaves as it does now, when it is not set it behaves like `Meta` currently does
* Completely remove `Meta` as all use cases can now be solved through `Aggregate`
* Add additional aggregators for boolean fields (`totalTrue`, `percentageTrue`, etc...)

## Todos 
* [x] in API
  * [x] make groupBy optional
  * [x] add missing aggregators
    * [x] string: `topOccurences`
    * [x] boolean: `totalTrue`, `percentageTrue`, `totalFalse`, `percentageFalse`
    * [x] `type`
    * [x] `meta count`
* [x] in repo
  * [x] when `groupBy` is not set, don't create per value buckets
    * [x] with single prop. single aggregator
    * [x] with multi prop, multi aggregator
  * [x] add missing aggregators
  * [x] support `meta count`
* [x] in traverser uc extend with type based on `schemaManager`
  * [x] property Types
  * [x] ref  prop pointing to
* [x] grep for `issues/949` and fix
* remove meta
  * [x] uc
  * [x] gql
* [x] remove support for untyped returns (i.e. always use `*aggregation.Result`)

**Comment by bobvanluijt** [comment]
That makes sense. Besides the "less is more" approach I'm agnostic about it.

**Comment by etiennedi** [comment]
@laura-ham Would love to hear your feedback on the above if you have a few minutes.

**Comment by laura-ham** [comment]
I agree that the functionality of `Meta` and `Aggregate` is similar, so I'm in for merging them. However, note that not only `topOccurrences` should be added to `Aggregate`, but also things like `percentageTrue` etc for boolean values, as you can see here https://github.com/semi-technologies/weaviate/blob/master/docs/en/use/graphql_local.md#meta-function.

**Comment by etiennedi** [comment]
Great point, thanks. I've added it to the above proposal.
