### ISSUE TITLE
Filter by cross-ref value in esvector 

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#962]
## Todos

* [x] one level deep
* [x] multiple levels deep
* [x] primitive props
* [x] geo props
* [x] create issue for cache boundary crossing
* [x] combine ref filter with primitive filter
