### ISSUE TITLE
Update cached objects when referenced object changes

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#963]
## Todos

* [x] Add option to schema manager to retrieve all possible paths to a class
  * ordered by level, so we can first refresh the inner ones
  * [x] one level deep
  * [x] infinitely deep
  * [x] respect depth limit
* [x] In repo at update/delete of a class 
  * [x] use schema manager to find possibilites of where this was referenced
  * [x] construct query to find all possible uuids
  * [x] batch update all uuids to cache stale and force refresh
