### ISSUE TITLE
Classification MVP

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#976]
Based on #948 

this is the *minimal* (focused on early delivery) Classfication feature. Limitations can be removed in future issues.

## Limitations
* We limit the classification to as many items as we can process in a single request to avoid having to build a work queue (this includes both training data and to be trained data)
* works only with cardinality `atMostOne`
* no limit on how many refs to classify at once

## Todos
* [ ] build simple REST API to trigger classification
* [ ] build classification runner
  * [ ] mark classification as started
  * [ ] get list of unclassified data (unclassified is at least one ref not set)
  * [ ] for each unclassified get n nearest neighbors, for each neighbor aggregate most common refs
  * [ ] accept ref, store upadted in mem
  * [ ] split up updates into sizeable bulk updates
  * [ ] mark classification as complete
* [ ] store classification state in repo (etcd?)
  * [ ] on `POST` assign ID, return to user
  * [ ] on `GET /id` return status
