### ISSUE TITLE
Add where filter to classifications

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#985]
Right now any source will be classified as any possible target. This issue aims to let the user both limit possible sources as well as possible targets.

## Example

Given the following sources: 
```
- name: Chocolate Cake
  glutenFree: false
- name: Special Bread
  glutenFree: true
```

and those targets:
```
- name: Gluten Free Savory Dish
- name: Gluten Free Sweet Dish
- name: Savory Dish (contains Gluten)
- name: Sweet Dish (contains Gluten)
```

I want to run two separate classifications:

- For all sources with `glutenFree: false`, possible targets include only target 3 and target 4
- For all sources with `glutenFree: true`, possible targets include only target 1 and 2

This is not possible with the current setup.

## Todos

* [x] Parse where filters in REST
  * [x] support flat filters
    * [x] for one operator
    * [x] for all operators (except geo)
    * [x] for one datatype
    * [x] for all primitive datatypes
    * [x] for geoprops
  * [x] support nested filters
  * [x] validate combinations (and/or and values, etc)
* [x] add to classifications uc for all three cases
* [x] validate that only filters are set which work for the specific type
* [x] include in repo/searches
  * [x] for knn
  * [x] for contextual

**Comment by fefi42** [comment]
there are two kinds of filters necessary one to limit the classified things and one that limits the set of samples used for classifying.

E.g. you want to classify products from one country based on products of the same country.

```
"classifyWhere": ...
"basedOnWhere":...
```

Maybe it makes sense to make the where field accept gql statements?

**Comment by etiennedi** [comment]
I think we need less ambiguous names for the filters. Coming back to this issue after some time, I can't immediately tell which property filters what. My suggestion would be:

`"sourceWhere" ` -> a source is always something that's to be classified, e.g. `Post`
`"targetWhere"` -> a target is always somethat that I can classify a source as, e.g. `Category`

Thoughts? @fefi42 @laura-ham @bobvanluijt

**Comment by fefi42** [comment]
Agree the names can be improved. Instead of `source` we could also use the machine learning lingo of `trainingSetWhere`.

**Comment by bobvanluijt** [comment]
I'm all for it, as long at is clearly described in the docs (cc: @laura-ham)

**Comment by etiennedi** [comment]
> Agree the names can be improved. Instead of `source` we could also use the machine learning lingo of `trainingSetWhere`.

@fefi42 Ah, I think we were actually talking about different things. As I understand it now there are actually three possible things to filter:

1. Unclassified Items -> "Only classify the currently unclassified items which match this criterium"
2. Training Set -> "When looking at training data, only use those already classified items which match this criterium"
3. Targets -> "When choosing possible targets only choose among those which match this criteria" <-- This one might be less relevant for knn, as this is already limited by which training set items point to which targets. But for a `contextual` classification we don't have such a restriction. 

Agreed?

**Comment by fefi42** [comment]
is 1. not the same as putting the same where clause into 2 and 3?

**Comment by etiennedi** [comment]
I don't think so - unless I'm missing something. Let me provide some examples.

# The dataset (same for all three examples)

Given the following unclassified:
```yaml
- name: Chocolate Cake
  color: black
- name: Wedding Cake
  color: white
- name: Cherry Pie
  color: red
```

with this training Data (knn):
```yaml
- name: Choc Tart
  classifiedAs: Cake
- name: Apple Pie
  classifiedAs: Pie
```


Possible Targets
```yaml
- name: Cake
- name: Pie
- name: Currywurst-Maultasche
```

# Examples

# Limiting Unclassified

> In this run, only classify those currently unclassified items which have `color != "red"`. 

I have some business knowledge about red items and want to classify them later using different metrics. Essentially the same as if no unclassified items with `color: red` existed in the dataset.

# Limit Training Data

> In this run, only compare my unclassified items to training set items where `name != "Apple Pie"`.

I have some business knowledge that Apple Pie is an unusal item so I don't want to it be part of my training data.  Essentially the same as if no training data item with `name: Applie Pie` existed.

# Limit Possible Targets

> In this run, make sure that none of my currently unclassified items can ever be classified as `name: Currywurst-Maultasche`

I have some business knowledge that - regardless of what the training data says - it should be impossible that any of my items should be classified as such.

**Comment by etiennedi** [comment]
Copy/Pasting from Slack between @fefi42 and me for completeness:

![image](https://user-images.githubusercontent.com/8974479/69964390-9d3f7e00-1512-11ea-9b5a-3ed2da1714eb.png)

So based on the above, my new suggestion for field names would be:

- `sourceWhere` (limit unclassified)
- `trainingSetWhere` (limit training set - can only be used on types with training sets, e.g. `knn`)
- `targetWhere` (limit possible targets - can only be used when targets don't depend on a training set, e.g. `contextual`)
